// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  dayby_day_itinerary: dynamic(() => import("./DaybyDayItinerary")),
  frequently_asked_questions: dynamic(
    () => import("./FrequentlyAskedQuestions"),
  ),
  hero_section: dynamic(() => import("./TopTourSummary")),
  highlights: dynamic(() => import("./Highlights")),
};
